upstream pgadmin_backend {
    server portfolio_pgadmin:80 max_fails=3 fail_timeout=30s;
}

server {
    listen 80;
    server_name 192.168.178.40;

    # Root - Landing Page
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /service-status/ {
        root /usr/share/nginx/html;

        # Prevent the browser from caching old status data
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        expires off;
    }

    location /dashboard/ {
        proxy_pass http://dashboard-ui:80;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }

    location /pgadmin/ {
        proxy_set_header X-Script-Name /pgadmin;
        proxy_set_header Host $host;

        # Use the upstream name here
        proxy_pass http://portfolio_pgadmin:80/; # This trailing slash is important!

        # Intercept errors to show a custom page if the container is down
        proxy_intercept_errors on;
        error_page 502 503 504 /custom_50x.html;
    }
}
