server {
    listen 80;
    server_name 192.168.178.40;

    # Root - Landing Page
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /service-status/ {
        root /usr/share/nginx/html;

        # Prevent the browser from caching old status data
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        expires off;
    }

    location /dashboard/ {
        proxy_pass http://dashboard-ui:80;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }
}
