services:
  # Please not that all variables must be present in `.env` parallel to this 
  # compose file or passed in via `--env-file`.

  backup-storage:
    image: ghcr.io/marvey11/achterhus-server-tools:latest
    command: ["backup-storage", "--source", "/mnt/storage", "--destination", "/mnt/mirror"]
    restart: "no"
    environment:
      - TELEMETRY_API_URL=http://telemetry-api:8000
    volumes:
      - /mnt/storage:/mnt/storage:ro
      - /mnt/backup/mirror:/mnt/mirror:rw
    networks:
      - achterhus-network

  sync-gdrive:
    image: ghcr.io/marvey11/achterhus-server-tools:latest
    command: ["sync-gdrive", "--gdrive-source", "${GDRIVE_SOURCE}", "--destination", "/mnt/gdrivesync"]
    restart: "no"
    environment:
      - TELEMETRY_API_URL=http://telemetry-api:8000
    volumes:
      - ${HOME}/.config/rclone:/home/appuser/.config/rclone:rw
      - ${HOST_SYNC_DIR}:/mnt/gdrivesync:rw
    networks:
      - achterhus-network

networks:
  achterhus-network:
    external: true
